[tool.black]
line-length = 79
target_version = ['py37']
exclude = '''

(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | \.misc
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''
